### ISSUE TITLE
Request for 6-DOF Pose Information for Each Frame

### ISSUE THREAD

**Issue by wzmsltw** [commaai/commavq#10]
I kindly request the project's author to provide 6-DOF pose information for each frame. The current implementation is useful, but I also need this additional data.

Please consider adding an option or API that allows accessing the 6-DOF pose information for every frame. This would greatly enhance the project's capabilities and benefit users with similar needs.

Thank you for considering this feature request.

**Comment by YassineYousfi** [comment]
We can (and will) opensource that in the future. 

Just curious, what are you currently building/trying with the 6DOF pose info?

**Comment by wzmsltw** [comment]
Thanks! 
I am interested in using 6DOF data as tokens for the GPT model, just like what was presented during the CommaCon event. Additionally, I believe that the 6DOF data might be useful for further exploring the challenging aspects of CommaVQ. This could potentially help optimize the model more effectively.

**Comment by YassineYousfi** [comment]
The pose data has been added here: 
https://huggingface.co/datasets/commaai/commavq/tree/main
Documentation and API coming soon

**Comment by wzmsltw** [comment]
Thanks! It will be very helpful.
