### ISSUE TITLE
InvalidProtobuf

### ISSUE THREAD

**Issue by johanngerberding** [commaai/commavq#12]
**Error description:**
InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/mojo/dev/commavq-challenge/commavq/models/decoder.onnx failed:Protobuf parsing failed.

This happens when I try to load the decoder model. 
When I try the checker 

`onnx.checker.check_model('../models/decoder.onnx')`

I get the following error: 
ValidationError: Unable to parse proto from file: /home/mojo/dev/commavq-challenge/commavq/models/decoder.onnx. Please check if it is a valid protobuf file of proto.

I am not sure if the onnx file is broken or this is an onnx problem? 

I tried onnxruntime-gpu and onnx 1.14 and 1.15, both times the same problem. 

Anyone else experiencing the same problems?

Is maybe this the problem?
https://github.com/onnx/onnx/blob/09a4e65bb098164491b021ffe563a559fbc1a808/docs/ExternalData.md

**Comment by YassineYousfi** [comment]
Not seeing this issue in onnxruntime-gpu 1.15.1 and 1.14.1. 

Are you sure you pulled the files correctly? They're stored in LFS.

**Comment by johanngerberding** [comment]
My bad, forgot the git lfs pull.
