### ISSUE TITLE
Inference Bounty

### ISSUE THREAD

**Issue by ae99** [commaai/commavq#21]
Hey @YassineYousfi!

Just learnt about this from your [talk](https://www.youtube.com/watch?v=-KMdo9AWJaQ) being (re)released, very cool!

Spent some time on the inference bounty, getting 0.2s per frame on 4090 and 0.28s on a 3090. May be more I can squeeze out, but not certain. 

Some quick questions:
- Is the bounty still open?
- Does a pure PyTorch solution with some startup time due to compilation fit your criteria?
- If yes to the above two, what's the standard process re: bounties?

**Comment by YassineYousfi** [comment]
Hey
- yeah the bounty is still open
- pure pytorch is fine, although the compile time is quite annoying (e.g. in https://github.com/pytorch-labs/gpt-fast/). is there a way to export the compiled model yet?
- once you're ready, you can send me the code, then we pay out the bounty if it runs at less than 0.25 sec/frame on my 3090 :)

**Comment by c5huracan** [comment]
Watched about half the presentation replay last night and was looking to see if these were solved. Any updates on this front https://github.com/YassineYousfi and https://github.com/ae99?

**Comment by ae99** [comment]
Hey! Sorry, busy week. Thanks @YassineYousfi!

Yes have solved this I think, just some tinkering on exporting to go!

**Comment by c5huracan** [comment]
@ae99 Cool, congratulations! Looking forward to seeing your solution.

**Comment by grekiki2** [comment]
Have you had any luck on this? TensorRT seems to be able to run the model at around 230-235ms/frame though with wrong outputs...

**Comment by ae99** [comment]
Abandoned for now, good luck!
