### ISSUE TITLE
"No such file or directory" when using HuggingFace dataset downloader

### ISSUE THREAD

**Issue by generic-github-user** [commaai/commavq#28]
On running the code sample from the README, or `compression/compress.py`, Python throws an `FileNotFoundError: [Errno 2] No such file or directory: '3b41c0fa8959aea6c118e5714f412a2e_13.npy` error (the files are not downloaded to the expected location). I did check `~/.cache/huggingface/datasets/commaai___commavq` and found some `.arrow` files, but the names do not match up with those specified by the dataset. Some help troubleshooting this would be much appreciated. Thanks!

**Comment by YassineYousfi** [comment]
can you make sure you install the version of huggingface datasets that’s listed in requirements.txt? I believe this is a recent behavior.
